export const catalogData = [
    {
        itransmission: 1,
        img: "../img/catalog/catalog1.jpeg",
        title: 'Subaru LEVORG VN5',
        year: 2021,
        capacity: 1.8,
        wheels: "4WD",
        fuel: "Бензин",
        transmission: "Вариатор",
        price: 2115600,
    },
    {
        itransmission: 2,
        img: '../img/catalog/catalog2.jpeg',
        title: 'Mazda Mazda6 2.5 AT Touring',
        year: 2020,
        capacity: 2.5,
        wheels: "Передний",
        fuel: "Бензин",
        transmission: "Автомат", 
        price: 2802400,
    },
    {
        itransmission: 3,
        img: '../img/catalog/catalog3.jpeg',
        title: 'Toyota CROWN AZSH21',
        year: 2019,
        capacity: 2.5,
        wheels: "4WD",
        fuel: "Гибрид",
        transmission: "Планетарная",
        price: 2852600,
    },
    {
        itransmission: 4,
        img: '../img/catalog/catalog4.jpeg',
        title: 'Lexus RC F USC10',
        year: 2019,
        capacity: 5.0,
        wheels: "Задний",
        fuel: "Бензин",
        transmission: "Автомат",
        price: 5965600,
    },
    {
        itransmission: 5,
        img: '../img/catalog/catalog5.jpeg',
        title: 'Mitsubishi ECLIPSE CROSS GK1W',
        year: 2019,
        capacity: 1.5,
        wheels: "Передний",
        fuel: "Бензин",
        transmission: "Вариатор",
        price: 2005200,
    },
    {
        itransmission: 6,
        img: '../img/catalog/catalog6.jpeg',
        title: 'Subaru IMPREZA WRX VAG',
        year: 2018,
        capacity: 2.0,
        wheels: "4WD",
        fuel: "Бензин",
        transmission: "Вариатор",
        price: 2852600,
    },
    {
        itransmission: 7,
        img: '../img/catalog/catalog7.jpeg',
        title: 'Lexus RX200T AGL20W',
        year: 2017,
        capacity: 2.0,
        wheels: "Передний",
        fuel: "Бензин",
        transmission: "Автомат",
        price: 2999800,
    },
    {
        itransmission: 8,
        img: '../img/catalog/catalog8.jpeg',
        title: 'Mitsubishi Outlander PHEV GG2W',
        year: 2013,
        capacity: 3.0,
        wheels: "4WD",
        fuel: "Бензин",
        transmission: "Автомат",
        price: 2366200,
    },
]